export const gstr2bHeaders = [
  { key: "gstin", label: "GSTIN of supplier" },
  { key: "tradeName", label: "Trade/Legal name" },
  { key: "invoiceNumber", label: "Invoice number" },
  { key: "invoiceType", label: "Invoice type" },
  { key: "invoiceDate", label: "Invoice Date" },
  { key: "invoiceValue", label: "Invoice Value (₹)" },
  { key: "placeOfSupply", label: "Place of supply" },
  { key: "reverseCharge", label: "Supply Attract Reverse Charge" },
  { key: "taxableValue", label: "Taxable Value (₹)" },
  { key: "igst", label: "Integrated Tax (₹)" },
  { key: "cgst", label: "Central Tax (₹)" },
  { key: "sgst", label: "State/UT Tax (₹)" },
  { key: "cess", label: "Cess (₹)" },
  { key: "gstrPeriod", label: "GSTR-1/1A/IFF/GSTR-5 Period" },
  { key: "gstrFilingDate", label: "GSTR-1/1A/IFF/GSTR-5 Filing Date" },
  { key: "itcAvailability", label: "ITC Availability" },
  { key: "reason", label: "Reason" },
  { key: "taxRatePercent", label: "Applicable % of Tax Rate" },
  { key: "source", label: "Source" },
  { key: "irn", label: "IRN" },
  { key: "irnDate", label: "IRN Date" },
];

